### ISSUE TITLE
Move warning on admin page into backdrop_set_message().

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/taxonomy_title#1]
On the admin page for taxonomy title, we check for the existence of the metatag module and set a warning: `Since you have either the page title module or the metatag module enabled, this module will be unable to affect the title tags of your pages. If you would like taxonomy titles to appear in your title tags, please configure that module to use the provided tokens. Example: [term-title]`

This should really be set using `backdrop_set_message` so that it can have the appropriate level of color.

**Comment by jenlampton** [comment]
The message should also be smarter about identifying which module it is that should be updated. Let's do a little `module_exists` magic and tell the user's exactly what's up.

**Comment by jenlampton** [comment]
fixed.

**Comment by klonos** [comment]
> The message should also be smarter about identifying which module it is that should be updated. Let's do a little `module_exists` magic and tell the user's exactly what's up.

How about [my alternative PR](https://github.com/backdrop-contrib/taxonomy_title/pull/7)? It accounts for any more interfering modules that might be possibly discovered in the future (simply add them to the `$problematic_modules_known` array), and also for the case where both metatag and page_title (or any combination and number of interfering modules for that mater) might be enabled in the same site at the same time.

Note: code untested.

**Comment by jenlampton** [comment]
Sorry @klonos, I didn't know you'd made a PR! I seem to be having a problem
accessing GitHub, I keep getting privacy errors with the HTTPS :( I'll have
a look, if I can ever get access again.

**Comment by klonos** [comment]
...thanx @jenlampton.

PS: Not sure that you wanted your phone number available there on your comment above, so I removed it for you. You can add it back if it was intentional.

**Comment by jenlampton** [comment]
@klonos I never want any of my contact info in there, unfortunately it gets added when I reply from my phone. Yesterday when I locked myself out of github that was what I was doing.  Thank you as usual for removing that for me :)

**Comment by klonos** [comment]
No worries 😉
