### ISSUE TITLE
Undefined index: tid in taxonomy_title_form_taxonomy_form_term_alter() 

### ISSUE THREAD

**Issue by YesCT** [backdrop-contrib/taxonomy_title#9]
Notice: Undefined index: tid in taxonomy_title_form_taxonomy_form_term_alter() (line 54 of modules/contrib/taxonomy_title/taxonomy_title.module).

**Comment by klonos** [comment]
...this is merged and included in [1.6.1](https://github.com/backdrop-contrib/taxonomy_title/releases/tag/1.x-1.6.1) 😉 👍
